services:
  phobos:
#    image: marsron/phobos:latest
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: phobos
    env_file: ".env"
    environment:
      NODE_ENV: production
    ports:
      - 8001:8001
    restart: unless-stopped
